version: "3"

services:

  server:
    environment:
    - NET=${NET}
    build: server/
    command: ./server.sh
    restart: always
    cap_add:
    - NET_ADMIN
    networks:
        network:
            ipv4_address: ${NET}.1.0
    expose:
      - "1-65535"

  client1:
    environment:
    - NET=${NET}
    build: client/
    command: ./client.sh
    restart: always
    networks:
        network:
          ipv4_address: ${NET}.1.1
    expose:
      - "1-65535"
    depends_on:
      - server

  client2:
    environment:
    - NET=${NET}
    build: client/
    command: ./client.sh
    restart: always
    networks:
        network:
          ipv4_address: ${NET}.2.2
    expose:
      - "1-65535"
    depends_on:
      - server

  client3:
    environment:
    - NET=${NET}
    build: client/
    command: ./client.sh
    restart: always
    networks:
        network:
          ipv4_address: ${NET}.3.3
    expose:
      - "1-65535"
    depends_on:
      - server

  client4:
    environment:
    - NET=${NET}
    build: client/
    command: ./client.sh
    restart: always
    networks:
        network:
          ipv4_address: ${NET}.4.4
    expose:
      - "1-65535"
    depends_on:
      - server

networks:
  network:
    ipam:
      config:
        - subnet: ${NET}.0.0/16
